apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-postgres-pvc
  labels:
    app: review-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: review-postgres
  labels:
    app: review-postgres
spec:
  serviceName: review-db
  replicas: 1
  selector:
    matchLabels:
      app: review-postgres
  template:
    metadata:
      labels:
        app: review-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          envFrom:
            - secretRef:
                name: review-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: review-db-data
          ports:
            - containerPort: 5432

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: review-db-data
          persistentVolumeClaim:
            claimName: review-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: review-db
spec:
  type: ClusterIP
  selector:
    app: review-postgres
  ports:
    - port: 5432